/**
 * Component Assembler
 * Assembles generated components into a complete, runnable agent
 */

import { AgentDefinition } from '../config/schema'
import { GeneratedComponent, generateComponentCode, GenerationOptions } from './generator'

/**
 * Assembled agent output
 */
export interface AssembledAgent {
  /** The agent definition */
  definition: AgentDefinition

  /** All generated component code */
  components: GeneratedComponent[]

  /** Main agent module code */
  mainModule: string

  /** Type definitions */
  typeDefinitions: string

  /** Package.json content if needed */
  packageJson?: string

  /** Build instructions */
  buildInstructions: string[]
}

/**
 * Assembly options
 */
export interface AssemblyOptions extends GenerationOptions {
  /** Output format */
  format?: 'single-file' | 'multi-file'

  /** Include package.json */
  includePackageJson?: boolean

  /** Module type */
  moduleType?: 'esm' | 'commonjs'
}

/**
 * Assemble an agent from its definition
 */
export function assembleAgent(
  definition: AgentDefinition,
  options: AssemblyOptions = {}
): AssembledAgent {
  const {
    format = 'single-file',
    includePackageJson = false,
    moduleType = 'esm'
  } = options

  // Generate all component code
  const components = generateComponentCode(definition, options)

  // Generate main module
  const mainModule = generateMainModule(definition, components, options)

  // Generate type definitions
  const typeDefinitions = generateTypeDefinitions(definition)

  // Generate package.json if needed
  const packageJson = includePackageJson
    ? generatePackageJson(definition, moduleType)
    : undefined

  // Build instructions
  const buildInstructions = generateBuildInstructions(format, moduleType)

  return {
    definition,
    components,
    mainModule,
    typeDefinitions,
    packageJson,
    buildInstructions
  }
}

/**
 * Generate the main agent module
 */
function generateMainModule(
  definition: AgentDefinition,
  components: GeneratedComponent[],
  options: AssemblyOptions
): string {
  const { format = 'single-file', moduleType = 'esm' } = options

  let code = `/**
 * ${definition.name}
 * ${definition.description}
 *
 * Auto-generated by Agent Builder
 * Version: ${definition.version}
 * Generated: ${new Date().toISOString()}
 */

`

  // Imports
  if (format === 'single-file') {
    code += `// Runtime types and utilities
interface ComponentExecutionContext {
  agentId: string
  executionId: string
  workingDirectory: string
  signal?: AbortSignal
  credentials: CredentialsStore
  state: StateStore
  logger: ComponentLogger
}

interface CredentialsStore {
  get(key: string): string | undefined
  set(key: string, value: string): void
  has(key: string): boolean
}

interface StateStore {
  get<T>(key: string): T | undefined
  set<T>(key: string, value: T): void
  delete(key: string): boolean
  clear(): void
}

interface ComponentLogger {
  debug(message: string, data?: unknown): void
  info(message: string, data?: unknown): void
  warn(message: string, data?: unknown): void
  error(message: string, error?: Error): void
}

interface RuntimeConnector {
  id: string
  initialize(): Promise<void>
  execute(operationId: string, params: Record<string, unknown>): Promise<unknown>
  isConnected(): boolean
  disconnect(): Promise<void>
  setContext?(context: ComponentExecutionContext): void
}

interface RuntimeProcessor {
  id: string
  process(input: unknown): Promise<unknown>
  setContext?(context: ComponentExecutionContext): void
}

interface RuntimeAction {
  id: string
  execute(data: unknown): Promise<ActionResult>
  canExecute(data: unknown): boolean
  getConnector(): RuntimeConnector
  setContext?(context: ComponentExecutionContext): void
}

interface RuntimeTrigger {
  id: string
  start(callback: TriggerCallback): void
  stop(): void
  isActive(): boolean
  invoke(): void
  setContext?(context: ComponentExecutionContext): void
}

interface ActionResult {
  success: boolean
  data?: unknown
  error?: string
}

type TriggerCallback = (context: TriggerContext) => Promise<void>

interface TriggerContext {
  triggerId: string
  triggerType: string
  triggeredAt: number
  payload?: unknown
}

interface ExecutionResult {
  success: boolean
  startedAt: number
  completedAt: number
  duration: number
  fetchedData: Map<string, unknown>
  processedData: Map<string, unknown>
  actionsExecuted: Array<{ actionId: string; result: ActionResult }>
  errors: Array<{ phase: string; componentId: string; message: string }>
}

`

    // Include all component code inline
    code += `// ============================================\n`
    code += `// Component Implementations\n`
    code += `// ============================================\n\n`

    for (const component of components) {
      code += `// --- ${component.type}: ${component.id} ---\n\n`
      // Remove import statements from inline code
      const cleanedCode = component.code
        .split('\n')
        .filter(line => !line.trim().startsWith('import '))
        .join('\n')
      code += cleanedCode + '\n\n'
    }
  } else {
    // Multi-file format - just import components
    const importStyle = moduleType === 'esm' ? 'import' : 'const'
    const fromStyle = moduleType === 'esm' ? 'from' : '= require'

    for (const component of components) {
      // Use the actual class name from the generated component, with fallback matching instantiation
      let className = component.className
      if (!className) {
        const suffix = component.type === 'connector' ? 'Connector'
          : component.type === 'processor' ? 'Processor'
          : component.type === 'action' ? 'Action'
          : 'Trigger'
        className = toPascalCase(component.id) + suffix
      }
      code += `${importStyle} { ${className} } ${fromStyle} './components/${component.id}'\n`
    }

    // Add runtime types import
    code += `${importStyle} {
  RuntimeConnector,
  RuntimeProcessor,
  RuntimeAction,
  RuntimeTrigger,
  ComponentExecutionContext,
  CredentialsStore,
  StateStore,
  ComponentLogger,
  TriggerContext,
  ExecutionResult,
  ActionResult
} ${fromStyle} './runtime-types'\n`
    code += '\n'
  }

  // Agent class
  code += `// ============================================
// Main Agent Class
// ============================================

export class ${toPascalCase(definition.name)}Agent {
  private definition = ${JSON.stringify(definition, null, 2)}

  private connectors = new Map<string, RuntimeConnector>()
  private processors = new Map<string, RuntimeProcessor>()
  private actions = new Map<string, RuntimeAction>()
  private triggers = new Map<string, RuntimeTrigger>()

  private context?: ComponentExecutionContext
  private running = false

  constructor(context?: Partial<ComponentExecutionContext>) {
    this.initializeComponents()

    if (context) {
      this.setContext({
        agentId: '${definition.id}',
        executionId: '',
        workingDirectory: context.workingDirectory || '.',
        credentials: context.credentials || createMemoryCredentials(),
        state: context.state || createMemoryState(),
        logger: context.logger || createConsoleLogger(),
        signal: context.signal
      })
    }
  }

  private initializeComponents(): void {
`

  // Initialize connectors
  const connectorComponents = components.filter(c => c.type === 'connector')
  for (const comp of connectorComponents) {
    const className = comp.className || toPascalCase(comp.id) + 'Connector'
    code += `    this.connectors.set('${comp.id}', new ${className}())\n`
  }

  // Initialize processors
  const processorComponents = components.filter(c => c.type === 'processor')
  for (const comp of processorComponents) {
    const className = comp.className || toPascalCase(comp.id) + 'Processor'
    code += `    this.processors.set('${comp.id}', new ${className}())\n`
  }

  // Initialize actions (need connector reference)
  const actionComponents = components.filter(c => c.type === 'action')
  for (const comp of actionComponents) {
    const className = comp.className || toPascalCase(comp.id) + 'Action'
    // Find the connector dependency
    const connectorId = comp.dependencies[0] || 'default'
    code += `    this.actions.set('${comp.id}', new ${className}(this.connectors.get('${connectorId}')!))\n`
  }

  // Initialize triggers
  const triggerComponents = components.filter(c => c.type === 'trigger')
  for (const comp of triggerComponents) {
    const className = comp.className || toPascalCase(comp.id) + 'Trigger'
    code += `    this.triggers.set('${comp.id}', new ${className}())\n`
  }

  code += `  }

  setContext(context: ComponentExecutionContext): void {
    this.context = context

    // Set context on all components
    for (const connector of this.connectors.values()) {
      if ('setContext' in connector) {
        (connector as { setContext: (ctx: ComponentExecutionContext) => void }).setContext(context)
      }
    }
    for (const processor of this.processors.values()) {
      if ('setContext' in processor) {
        (processor as { setContext: (ctx: ComponentExecutionContext) => void }).setContext(context)
      }
    }
    for (const action of this.actions.values()) {
      if ('setContext' in action) {
        (action as { setContext: (ctx: ComponentExecutionContext) => void }).setContext(context)
      }
    }
    for (const trigger of this.triggers.values()) {
      if ('setContext' in trigger) {
        (trigger as { setContext: (ctx: ComponentExecutionContext) => void }).setContext(context)
      }
    }
  }

  async initialize(): Promise<void> {
    this.context?.logger.info('Initializing ${definition.name}...')

    // Initialize all connectors
    for (const [id, connector] of this.connectors) {
      this.context?.logger.info(\`Initializing connector: \${id}\`)
      await connector.initialize()
    }

    this.context?.logger.info('${definition.name} initialized')
  }

  async start(): Promise<void> {
    if (this.running) {
      this.context?.logger.warn('Agent already running')
      return
    }

    this.running = true
    this.context?.logger.info('Starting ${definition.name}...')

    // Start all triggers
    for (const [id, trigger] of this.triggers) {
      this.context?.logger.info(\`Starting trigger: \${id}\`)
      trigger.start(async (ctx) => {
        await this.runOnce(ctx)
      })
    }

    this.context?.logger.info('${definition.name} started')
  }

  async stop(): Promise<void> {
    this.running = false
    this.context?.logger.info('Stopping ${definition.name}...')

    // Stop all triggers
    for (const trigger of this.triggers.values()) {
      trigger.stop()
    }

    // Disconnect all connectors
    for (const connector of this.connectors.values()) {
      await connector.disconnect()
    }

    this.context?.logger.info('${definition.name} stopped')
  }

  async runOnce(triggerContext?: TriggerContext): Promise<ExecutionResult> {
    const startedAt = Date.now()
    const executionId = \`exec_\${Date.now()}\`

    if (this.context) {
      this.context.executionId = executionId
    }

    const result: ExecutionResult = {
      success: false,
      startedAt,
      completedAt: 0,
      duration: 0,
      fetchedData: new Map(),
      processedData: new Map(),
      actionsExecuted: [],
      errors: []
    }

    try {
      this.context?.logger.info(\`Starting execution \${executionId}\`)

      // Phase 1: Fetch data from connectors
      for (const [id, connector] of this.connectors) {
        try {
          // TODO: Execute appropriate operations based on agent logic
          this.context?.logger.info(\`Fetching from connector: \${id}\`)
          // const data = await connector.execute('operation', {})
          // result.fetchedData.set(id, data)
        } catch (error) {
          result.errors.push({
            phase: 'fetch',
            componentId: id,
            message: error instanceof Error ? error.message : String(error)
          })
        }
      }

      // Phase 2: Process data through processors
      for (const [id, processor] of this.processors) {
        try {
          this.context?.logger.info(\`Processing with: \${id}\`)
          // TODO: Pass appropriate input data
          // const processed = await processor.process(input)
          // result.processedData.set(id, processed)
        } catch (error) {
          result.errors.push({
            phase: 'process',
            componentId: id,
            message: error instanceof Error ? error.message : String(error)
          })
        }
      }

      // Phase 3: Execute actions
      for (const [id, action] of this.actions) {
        try {
          this.context?.logger.info(\`Executing action: \${id}\`)
          // TODO: Check approval requirements
          // const actionResult = await action.execute(data)
          // result.actionsExecuted.push({ actionId: id, result: actionResult })
        } catch (error) {
          result.errors.push({
            phase: 'action',
            componentId: id,
            message: error instanceof Error ? error.message : String(error)
          })
        }
      }

      result.success = result.errors.length === 0
    } catch (error) {
      this.context?.logger.error('Execution failed', error as Error)
      result.errors.push({
        phase: 'action',
        componentId: 'agent',
        message: error instanceof Error ? error.message : String(error)
      })
    }

    result.completedAt = Date.now()
    result.duration = result.completedAt - result.startedAt

    this.context?.logger.info(
      \`Execution \${executionId} completed in \${result.duration}ms (success: \${result.success})\`
    )

    return result
  }

  getStatus(): {
    running: boolean
    connectors: { id: string; connected: boolean }[]
    triggers: { id: string; active: boolean }[]
  } {
    return {
      running: this.running,
      connectors: Array.from(this.connectors.entries()).map(([id, c]) => ({
        id,
        connected: c.isConnected()
      })),
      triggers: Array.from(this.triggers.entries()).map(([id, t]) => ({
        id,
        active: t.isActive()
      }))
    }
  }
}

// ============================================
// Utility Functions
// ============================================

function createMemoryCredentials(): CredentialsStore {
  const store = new Map<string, string>()
  return {
    get: (key: string) => store.get(key),
    set: (key: string, value: string) => { store.set(key, value) },
    has: (key: string) => store.has(key)
  }
}

function createMemoryState(): StateStore {
  const store = new Map<string, unknown>()
  return {
    get: <T>(key: string) => store.get(key) as T | undefined,
    set: <T>(key: string, value: T) => { store.set(key, value) },
    delete: (key: string) => store.delete(key),
    clear: () => store.clear()
  }
}

function createConsoleLogger(): ComponentLogger {
  return {
    debug: (msg: string, data?: unknown) => console.log('[DEBUG]', msg, data || ''),
    info: (msg: string, data?: unknown) => console.log('[INFO]', msg, data || ''),
    warn: (msg: string, data?: unknown) => console.warn('[WARN]', msg, data || ''),
    error: (msg: string, error?: Error) => console.error('[ERROR]', msg, error || '')
  }
}

// ============================================
// Exports
// ============================================

export default ${toPascalCase(definition.name)}Agent

// Export for direct execution
if (typeof require !== 'undefined' && require.main === module) {
  const agent = new ${toPascalCase(definition.name)}Agent()
  agent.initialize()
    .then(() => agent.start())
    .catch(console.error)
}
`

  return code
}

/**
 * Generate type definitions
 */
function generateTypeDefinitions(definition: AgentDefinition): string {
  return `/**
 * Type definitions for ${definition.name}
 * Auto-generated by Agent Builder
 */

export interface ${toPascalCase(definition.name)}Config {
  credentials?: {
${definition.components.connectors.map(c => {
  switch (c.auth.type) {
    case 'api_key':
      return `    ${c.id}_api_key?: string`
    case 'oauth2':
      return `    ${c.id}_access_token?: string
    ${c.id}_refresh_token?: string`
    case 'basic':
      return `    ${c.id}_username?: string
    ${c.id}_password?: string`
    default:
      return ''
  }
}).filter(Boolean).join('\n')}
  }
  workingDirectory?: string
}

export interface ${toPascalCase(definition.name)}ExecutionResult {
  success: boolean
  duration: number
  errors: string[]
}
`
}

/**
 * Generate package.json
 */
function generatePackageJson(definition: AgentDefinition, moduleType: 'esm' | 'commonjs'): string {
  const pkg = {
    name: definition.name.toLowerCase().replace(/\s+/g, '-'),
    version: definition.version,
    description: definition.description,
    type: moduleType === 'esm' ? 'module' : 'commonjs',
    main: moduleType === 'esm' ? 'dist/index.js' : 'dist/index.cjs',
    types: 'dist/index.d.ts',
    scripts: {
      build: 'tsc',
      start: 'node dist/index.js',
      dev: 'ts-node src/index.ts'
    },
    dependencies: {
      'node-fetch': '^3.3.0'
    },
    devDependencies: {
      typescript: '^5.0.0',
      'ts-node': '^10.9.0',
      '@types/node': '^20.0.0'
    },
    engines: {
      node: '>=18.0.0'
    }
  }

  return JSON.stringify(pkg, null, 2)
}

/**
 * Generate build instructions
 */
function generateBuildInstructions(format: string, moduleType: string): string[] {
  return [
    '1. Install dependencies: npm install',
    '2. Configure credentials in environment or .env file',
    '3. Build: npm run build',
    '4. Run: npm start',
    '',
    `Format: ${format}`,
    `Module type: ${moduleType}`,
    '',
    'Environment variables needed:',
    '  - Set credentials for each connector',
    '  - See type definitions for required keys'
  ]
}

/**
 * Convert string to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
}

/**
 * Export agent as a single file string
 */
export function exportAgentAsString(assembled: AssembledAgent): string {
  return assembled.mainModule
}

/**
 * Export agent as multiple files
 */
export function exportAgentAsFiles(assembled: AssembledAgent): Map<string, string> {
  const files = new Map<string, string>()

  // Main file
  files.set('index.ts', assembled.mainModule)

  // Type definitions
  files.set('types.d.ts', assembled.typeDefinitions)

  // Component files
  for (const component of assembled.components) {
    files.set(`components/${component.id}.ts`, component.code)
  }

  // Package.json
  if (assembled.packageJson) {
    files.set('package.json', assembled.packageJson)
  }

  // README with build instructions
  const readme = `# ${assembled.definition.name}

${assembled.definition.description}

## Setup

${assembled.buildInstructions.join('\n')}

## Generated by Agent Builder

Version: ${assembled.definition.version}
`
  files.set('README.md', readme)

  return files
}
